#!/bin/bash

#  - autocd, no need to type 'cd' when changing directory
#  - cdspell, automatically fix directory typos when changing directory
#  - direxpand, automatically expand directory globs when completing
#  - dirspell, automatically fix directory typos when completing
#  - nocaseglob, case-insensitive globbing
shopt -s autocd cdspell direxpand dirspell nocaseglob

HISTSIZE= HISTFILESIZE= # Infinite history.
if [ ! -z $TERM ]; then
    export PS1="\[\033[1;31m\]\$(RET=\$?; [ \$RET != 0 -a \$RET != 130 ] && echo -n \$RET\ )\[\033[1;33m\]\W \[\033[1;32m\]> \[\033[0m\]"
fi

# vi-mode
set -o vi

# color
alias ls='ls -N --color=auto --group-directories-first'
alias grep="grep --color=auto"
alias diff="diff --color=auto"

# clear
bind -x '"\C-l": clear'
# clear and ls
bind -x '"\el": clear; ls'

# get a file or directory
fzf_file() {
    base_dir=$1
    sel=$(locate "${base_dir}*" | fzf)
    printf '%s' "$sel"
}

# get a directory with fzf
fzf_dir() {
    sel=$(fzf_file $1)
    [ -f $sel ] && sel=$(dirname "$sel")
    printf '%s' "$sel"
}

# get entry from command history
fzf_history() {
  line=$(history | fzf)
  sed 's/^[0-9 ]*//' <<< "$line"
}

# needed below
bind '"\C-x\C-a": vi-movement-mode'
bind '"\C-x\C-e": shell-expand-line'

# various cd helpers
alias c='cd "$(fzf_dir $PWD)"'
alias ch='cd "$(fzf_dir $HOME)"'
alias cg='cd "$(fzf_dir /)"'
bind '"\ec": "cd `fzf_dir $PWD`\C-x\C-e\C-m"'

# insert filename
bind '"\ef": "`fzf_file $PWD`\C-x\C-e"'

# find with fzf and open in editor
bind -x '"\ee": locate "$PWD" | fzf --preview="head -$LINES {}" | xargs -r nvim'
alias e='locate "$PWD*" | fzf --preview="head -$LINES {}" | xargs -r nvim'
alias eh='locate "$HOME*" | fzf --preview="head -$LINES {}" | xargs -r sudo nvim'
alias eg='locate "/*" | fzf --preview="head -$LINES {}" | xargs -r sudo nvim'

# search history with fzf
bind '"\er": "`fzf_history`\C-x\C-e\C-x\C-a$a"'
bind -m vi-command '"\er": "i\C-r"'

# open ssh connection with fzf
bind -x '"\es": fzf_ssh'
alias fs=fzf_ssh

# M-i to insert word from current tmux pane
bind -x '"\ei": tmux_copy'

# M-d to show tasks with taskwarrior
bind -x '"\ed": clear; task'

# clear line
bind '"\ew": kill-whole-line'
bind -m vi-command '"\ew": kill-whole-line'

# other aliases
alias del=trash
alias fsc=fzf_scp
alias fk=fzf_kill
alias ss='sudo systemctl'
alias v='nvim'
alias ka='killall'

alias p='pacman'
alias pss='pacman -Ss'
alias sp='sudo pacman'
alias sps='sudo pacman -S'
alias spy='sudo pacman -Sy'

alias g='git'
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gd='git diff'
alias gl='git log'
alias gpl='git pull'
alias gps='git push'

alias cht='cht.sh'
alias trde='trans de:en -v -theme random'
alias tred='trans en:de -v -theme random'
