set nocompatible
filetype indent plugin on
syntax on

colo delek 

set hidden
set wildmenu
set showcmd

set hlsearch
set ignorecase
set smartcase
 
" Allow backspacing over autoindent, line breaks and start of insert action
set backspace=indent,eol,start
set autoindent
set nostartofline
 
" Display the cursor position on the last line of the screen or in the status
" line of a window
set ruler
 
" Always display the status line, even if only one window is displayed
set laststatus=2
 
" Instead of failing a command because of unsaved changes, instead raise a
" dialogue asking if you wish to save changed files.
set confirm
 
set visualbell
set t_vb=
 
set mouse=
 
set cmdheight=2
set notimeout ttimeout ttimeoutlen=200
 
set shiftwidth=4
set softtabstop=4
set expandtab
 
map Y y$
 
nnoremap <C-L> :nohl<CR><C-L>
 
set scrolloff=15
