#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

[ -f $sysresources ] && xrdb -merge $sysresources
[ -f $sysmodmap ] && xmodmap -merge $sysmodmap
[ -f $userresources ] && xrdb -merge $userresources
[ -f $usermodmap ] && xmodmap -merge $usermodmap

# fix for java applications in dwm
export _JAVA_AWT_WM_NONREPARENTING=1

# set keyboard layout
setxkbmap de
sxhkd &
sleep 5 && setxkbmap lv && xmodmap ~/my_neo_de.xmodmap && xset -r 51 &

set_wallpaper &

# start some programs
clipmenud &
dunst &
nm-applet &
sleep 10 && compton -b &
redshift &
# other machine dependent program
~/.start_jobs &

# start the window manager
{%@@ if wm == "i3" @@%}
i3
{%@@ elif wm == "awesome" @@%}
awesome
{%@@ elif wm == "bspwm" @@%}
bspwm
{%@@ endif @@%}
