#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

[ -f $sysresources ] && xrdb -merge $sysresources
[ -f $sysmodmap ] && xmodmap -merge $sysmodmap
[ -f $userresources ] && xrdb -merge $userresources
[ -f $usermodmap ] && xmodmap -merge $usermodmap

# fix for java applications in dwm
export _JAVA_AWT_WM_NONREPARENTING=1

# start sxhkd before setting my keyboard layout
setxkbmap de
sxhkd &

# set keyboard layout
sleep 5 && setxkbmap lv && xmodmap ~/my_neo_de.xmodmap && xset -r 51 &

# set key repitition rate and delay
xset r rate 300 40

set_wallpaper &

# start some programs
clipmenud &
dunst &
nm-applet &
compton -b &
redshift &

# other machine dependent program
~/.start_jobs &

# start the window manager
{%@@ if wm == "bspwm" @@%}
bspwm
{%@@ elif wm == "dwm" @@%}

sleep 5 && dwmblocks &

while true; do
    dwm > $HOME/.dwm.log 2>&1
done
{%@@ endif @@%}
