#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

[ -f $sysresources ] && xrdb -merge $sysresources
[ -f $sysmodmap ] && xmodmap -merge $sysmodmap
[ -f $userresources ] && xrdb -merge $userresources
[ -f $usermodmap ] && xmodmap -merge $usermodmap

# start some programs
sxhkd &
setxkbmap lv && xmodmap ~/my_neo_de.xmodmap && xset -r 51 &
clipmenud &
dunst &
nm-applet &
sleep 5 && xmouseless &
sleep 20 && dropbox start &
compton -b &
redshift &
set_wallpaper &

# set status bar content
while true; do
    dwm_status
    sleep 1
done &

while true; do
    exec dwm > $HOME/.dwm.log 2>&1
done
