#          _     
#  _______| |__  
# |_  / __| '_ \ 
#  / /\__ \ | | |
# /___|___/_| |_|
#               

# history
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000
setopt hist_ignore_space

# completion
setopt autocd extendedglob
unsetopt beep
bindkey -v
zstyle :compinstall filename '/home/jbensmann/.zshrc'

autoload -Uz compinit
autoload -U colors && colors
PS1="%B%{$fg[yellow]%}[%~]%{$reset_color%}%b "

zstyle ':completion:*' menu select
zmodload zsh/complist
compinit

# Include hidden files in autocomplete:
_comp_options+=(globdots)

# Use vim keys in tab complete menu:
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -v '^?' backward-delete-char

export KEYTIMEOUT=1

# Change cursor shape for different vi modes.
function zle-keymap-select {
  if [[ ${KEYMAP} == vicmd ]] ||
     [[ $1 = 'block' ]]; then
    echo -ne '\e[1 q'

  elif [[ ${KEYMAP} == main ]] ||
       [[ ${KEYMAP} == viins ]] ||
       [[ ${KEYMAP} = '' ]] ||
       [[ $1 = 'beam' ]]; then
    echo -ne '\e[5 q'
  fi
}

# fzf
source /usr/share/fzf/completion.zsh
source /usr/share/fzf/key-bindings.zsh

# get a directory with fzf
_fzf_dir() {
    sel=$(fzf)
    [ -f $sel ] && sel=$(dirname "$sel")
    printf '%s' "$sel"
}

# find with fzf and open in editor
alias e='fzf --preview="head -$LINES {}" | xargs -r nvim'
alias eg='locate "/*" | fzf --preview="head -$LINES {}" | xargs -r sudo nvim'
alias vg='locate "/*" | fzf --preview="head -$LINES {}" | xargs -r nvim'


# M-i to insert word from current tmux pane
_tmux_copy() { tmux_copy }
zle -N _tmux_copy
bindkey '^[i' _tmux_copy

# M-d to show tasks with taskwarrior
_task() { clear; task }
zle -N _task
bindkey '^[d' _task

# open ssh connection with fzf
_fzf_ssh() { fzf_ssh }
zle -N _fzf_ssh
bindkey '^[s' _fzf_ssh

# other aliases
alias fk=fzf_kill
alias ss='sudo systemctl'
alias v='nvim'
alias ka='killall'

alias p='pacman'
alias pss='pacman -Ss'
alias sp='sudo pacman'
alias spy='sudo pacman -Sy'
alias sps='sudo pacman -S'
alias spr='sudo pacman -Rns'

alias g='git'
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gd='git diff'
alias gl='git log'
alias gpl='git pull'
alias gps='git push'

alias ta='task add'
alias tm='task modify'
alias td='task done'
alias tdel='task delete'

alias cht='cht.sh'
alias trde='trans de:en -v -theme random'
alias tred='trans en:de -v -theme random'

