#          _     
#  _______| |__  
# |_  / __| '_ \ 
#  / /\__ \ | | |
# /___|___/_| |_|
#               

# history
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000
setopt hist_ignore_space

# completion
setopt autocd extendedglob
unsetopt beep
bindkey -v
zstyle :compinstall filename '/home/jbensmann/.zshrc'

autoload -Uz compinit
autoload -U colors && colors
PS1="%B%{$fg[yellow]%}[%~]%{$reset_color%}%b "

zstyle ':completion:*' menu select
zmodload zsh/complist
compinit

# Include hidden files in autocomplete:
_comp_options+=(globdots)

# Use vim keys in tab complete menu:
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -v '^?' backward-delete-char

export KEYTIMEOUT=1

# Change cursor shape for different vi modes.
function zle-keymap-select {
  if [[ ${KEYMAP} == vicmd ]] ||
     [[ $1 = 'block' ]]; then
    echo -ne '\e[1 q'

  elif [[ ${KEYMAP} == main ]] ||
       [[ ${KEYMAP} == viins ]] ||
       [[ ${KEYMAP} = '' ]] ||
       [[ $1 = 'beam' ]]; then
    echo -ne '\e[5 q'
  fi
}

# Use beam shape cursor on startup.
echo -ne '\e[5 q'
# Use beam shape cursor for each new prompt.
preexec() { echo -ne '\e[5 q' ;}


# color
alias ls='ls -N --color=auto --group-directories-first'
alias grep="grep --color=auto"
alias diff="diff --color=auto"


# fzf
source /usr/share/fzf/completion.zsh
source /usr/share/fzf/key-bindings.zsh

# find with fzf and open in editor
alias e='fzf --preview="head -$LINES {}" | xargs -r nvim'
alias eg='locate "/*" | fzf --preview="head -$LINES {}" | xargs -r sudo nvim'
alias vg='locate "/*" | fzf --preview="head -$LINES {}" | xargs -r nvim'


# M-i to insert word from current tmux pane
_tmux_copy() { tmux_copy }
zle -N _tmux_copy
bindkey '^[i' _tmux_copy

# M-d to show tasks with taskwarrior
bindkey -s '^[d' 'clear; task\n'

# M-l for ls
bindkey -s '^[l' 'ls\n'

# C-k to kill process with fzf
bindkey -s '^k' 'kill \t'

# M-s to open ssh connection with fzf
bindkey -s '^[s' 'fzf_ssh\n'

# M-f as alternative to C-t (select file)
bindkey '^[f' fzf-file-widget

# other aliases
alias fk=fzf_kill
alias ss='sudo systemctl'
alias v='nvim'
alias ka='killall'

alias p='pacman'
alias pss='pacman -Ss'
alias sp='sudo pacman'
alias spy='sudo pacman -Sy'
alias sps='sudo pacman -S'
alias spr='sudo pacman -Rns'

alias fp='sudo pacman -S $(pacman -Ss | paste - - | fzf | awk '\''{print $1}'\'')'
function ft {
    trizen -S $(trizen -Ss $1 | paste - - | fzf | awk '{print $1}')
}

alias g='git'
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gd='git diff'
alias gl='git log'
alias gpl='git pull'
alias gps='git push'

alias cht='cht.sh'
alias trde='trans de:en -v -theme random'
alias tred='trans en:de -v -theme random'

# syntax highlighting
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)
# commands starting with rm in red
ZSH_HIGHLIGHT_PATTERNS=('rm *' 'fg=white,bold,bg=red')
