#! /bin/sh

~/.config/polybar/launch.sh

{%@@ if monitor2 is defined @@%}
bspc monitor {{@@ monitor1 @@}} -d 2 3 4 5 0
bspc monitor {{@@ monitor2 @@}} -d 1 6 7 8 9 
{%@@ elif monitor1 is defined @@%}
bspc monitor {{@@ monitor1 @@}} -d 1 2 3 4 5 6 7 8 9 0
{%@@ else @@%}
bspc monitor -d 1 2 3 4 5 6 7 8 9 0
{%@@ endif @@%}

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on

