config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_by_default: false
  longkey: false
dotfiles:
  d_bin:
    dst: ~/bin
    src: bin
  d_ranger:
    dst: ~/.config/ranger
    src: config/ranger
  f_bashrc:
    dst: ~/.bashrc
    src: bashrc
  f_compton.conf:
    dst: ~/.config/compton/compton.conf
    src: config/compton/compton.conf
  f_dunstrc:
    dst: ~/.config/dunst/dunstrc
    src: config/dunst/dunstrc
  f_emoji:
    dst: ~/.emoji
    src: emoji
  f_fa_icons:
    dst: ~/.fa_icons
    src: fa_icons
  f_i3_config:
    dst: ~/.i3/config
    src: i3/config
  f_ideavimrc:
    dst: ~/.ideavimrc
    src: ideavimrc
  f_init.vim:
    dst: ~/.config/nvim/init.vim
    src: config/nvim/init.vim
  f_inputrc:
    dst: ~/.inputrc
    src: inputrc
  f_lfrc:
    dst: ~/.config/lf/lfrc
    src: config/lf/lfrc
  f_morc_menu_v1.conf:
    dst: ~/.config/morc_menu/morc_menu_v1.conf
    src: config/morc_menu/morc_menu_v1.conf
  f_my_neo_de.xmodmap:
    dst: ~/my_neo_de.xmodmap
    src: my_neo_de.xmodmap
  f_polybar_config:
    dst: ~/.config/polybar/config
    src: config/polybar/config
  f_polybar_launch.sh:
    dst: ~/.config/polybar/launch.sh
    src: config/polybar/launch.sh
  f_profile:
    dst: ~/.profile
    src: profile
  f_redshift.conf:
    dst: ~/.config/redshift/redshift.conf
    src: config/redshift/redshift.conf
  f_sxhkdrc:
    dst: ~/.config/sxhkd/sxhkdrc
    src: config/sxhkd/sxhkdrc
  f_taskrc:
    dst: ~/.taskrc
    src: taskrc
  f_termite_config:
    dst: ~/.config/termite/config
    src: config/termite/config
  f_tmux.conf:
    dst: ~/.tmux.conf
    src: tmux.conf
  f_vimrc:
    dst: ~/.vimrc
    src: vimrc
  f_wallpaper.jpg:
    dst: ~/.config/wallpaper.jpg
    src: config/wallpaper.jpg
  f_xinitrc:
    dst: ~/.xinitrc
    src: xinitrc
  f_zathurarc:
    dst: ~/.config/zathura/zathurarc
    src: config/zathura/zathurarc
profiles:
  desktop-i3:
    dotfiles:
    - d_bin
    - d_ranger
    - f_lfrc
    - f_bashrc
    - f_dunstrc
    - f_emoji
    - f_fa_icons
    - f_ideavimrc
    - f_init.vim
    - f_vimrc
    - f_morc_menu_v1.conf
    - f_my_neo_de.xmodmap
    - f_profile
    - f_redshift.conf
    - f_sxhkdrc
    - f_taskrc
    - f_tmux.conf
    - f_xinitrc
    - f_inputrc
    - f_zathurarc
    - f_compton.conf
  jb-work:
    dotfiles:
    - d_bin
    - d_ranger
    - f_lfrc
    - f_bashrc
    - f_dunstrc
    - f_emoji
    - f_fa_icons
    - f_ideavimrc
    - f_init.vim
    - f_vimrc
    - f_morc_menu_v1.conf
    - f_my_neo_de.xmodmap
    - f_profile
    - f_redshift.conf
    - f_sxhkdrc
    - f_taskrc
    - f_tmux.conf
    - f_xinitrc
    - f_inputrc
    - f_zathurarc
    - f_compton.conf
  laptop-i3:
    dotfiles:
    - d_bin
    - d_ranger
    - f_lfrc
    - f_bashrc
    - f_dunstrc
    - f_emoji
    - f_fa_icons
    - f_ideavimrc
    - f_init.vim
    - f_vimrc
    - f_morc_menu_v1.conf
    - f_my_neo_de.xmodmap
    - f_profile
    - f_redshift.conf
    - f_sxhkdrc
    - f_taskrc
    - f_tmux.conf
    - f_inputrc
    - f_xinitrc
    - f_zathurarc
    - d_bin
    - f_compton.conf
