config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_by_default: false
  longkey: false
dotfiles:
  d_fonts:
    dst: ~/.fonts
    src: fonts
  d_qpdfview:
    dst: ~/.config/qpdfview
    src: config/qpdfview
  f_config:
    dst: ~/.i3/config
    src: i3/config
  f_jojo.zsh-theme:
    dst: ~/.oh-my-zsh/themes/jojo.zsh-theme
    src: oh-my-zsh/themes/jojo.zsh-theme
  f_launch.sh:
    dst: ~/.config/polybar/launch.sh
    src: config/polybar/launch.sh
  f_polybar_config:
    dst: ~/.config/polybar/config
    src: config/polybar/config
  f_rc.conf:
    dst: ~/.config/ranger/rc.conf
    src: config/ranger/rc.conf
  f_redshift.conf:
    dst: ~/.config/redshift/redshift.conf
    src: config/redshift/redshift.conf
  f_resize-font:
    dst: ~/.urxvt/ext/resize-font
    src: urxvt/ext/resize-font
  f_spacemacs:
    dst: ~/.spacemacs
    src: spacemacs
  f_tmux.conf:
    dst: ~/.tmux.conf
    src: tmux.conf
  f_vimrc:
    dst: ~/.vimrc
    src: vimrc
  f_wallpaper.jpg:
    dst: ~/.config/wallpaper.jpg
    src: config/wallpaper.jpg
  f_xinitrc:
    dst: ~/.xinitrc
    src: xinitrc
  f_xmodmap:
    dst: ~/.Xmodmap
    src: Xmodmap
  f_xresources:
    dst: ~/.Xresources
    src: Xresources
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
profiles:
  desktop-i3:
    dotfiles:
    - f_config
    - f_spacemacs
    - f_rc.conf
    - f_vimrc
    - f_xinitrc
    - f_xresources
    - f_xmodmap
    - d_fonts
    - f_polybar_config
    - f_launch.sh
    - d_qpdfview
    - f_redshift.conf
    - f_resize-font
    - f_zshrc
    - f_jojo.zsh-theme
    - f_tmux.conf
  laptop-i3:
    dotfiles:
    - f_config
    - f_spacemacs
    - f_xresources
    - f_xmodmap
    - f_rc.conf
    - d_fonts
    - f_polybar_config
    - f_launch.sh
    - d_qpdfview
    - f_redshift.conf
    - f_resize-font
    - f_zshrc
    - f_jojo.zsh-theme
    - f_tmux.conf
