config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  longkey: false
  link_on_import: nolink
  minversion: 0.30.0
dotfiles:
  d_awesome:
    dst: ~/.config/awesome
    src: config/awesome
  d_bin:
    dst: ~/bin
    src: bin
  d_oni2:
    dst: ~/.config/oni2
    src: config/oni2
  d_ranger:
    dst: ~/.config/ranger
    src: config/ranger
  d_vscode:
    dst: ~/.config/Code - OSS/User
    src: config/vscode/User
  f_alacritty.yml:
    dst: ~/.config/alacritty/alacritty.yml
    src: config/alacritty/alacritty.yml
  f_bashrc:
    dst: ~/.bashrc
    src: bashrc
  f_coc-settings.json:
    dst: ~/.config/nvim/coc-settings.json
    src: config/nvim/coc-settings.json
  f_compton.conf:
    dst: ~/.config/compton/compton.conf
    src: config/compton/compton.conf
  f_dunstrc:
    dst: ~/.config/dunst/dunstrc
    src: config/dunst/dunstrc
  f_emoji:
    dst: ~/.emoji
    src: emoji
  f_fa_icons:
    dst: ~/.fa_icons
    src: fa_icons
  f_i3_config:
    dst: ~/.config/i3/config
    src: config/i3/config
  f_ideavimrc:
    dst: ~/.ideavimrc
    src: ideavimrc
  f_init.vim:
    dst: ~/.config/nvim/init.vim
    src: config/nvim/init.vim
  f_inputrc:
    dst: ~/.inputrc
    src: inputrc
  f_lfrc:
    dst: ~/.config/lf/lfrc
    src: config/lf/lfrc
  f_linopenrc:
    dst: ~/.linopenrc
    src: linopenrc
  f_morc_menu_v1.conf:
    dst: ~/.config/morc_menu/morc_menu_v1.conf
    src: config/morc_menu/morc_menu_v1.conf
  f_my_neo_de.xmodmap:
    dst: ~/my_neo_de.xmodmap
    src: my_neo_de.xmodmap
  f_polybar_config:
    dst: ~/.config/polybar/config
    src: config/polybar/config
  f_polybar_launch.sh:
    dst: ~/.config/polybar/launch.sh
    src: config/polybar/launch.sh
  f_profile:
    dst: ~/.profile
    src: profile
  f_redshift.conf:
    dst: ~/.config/redshift/redshift.conf
    src: config/redshift/redshift.conf
  f_sxhkdrc:
    dst: ~/.config/sxhkd/sxhkdrc
    src: config/sxhkd/sxhkdrc
  f_taskrc:
    dst: ~/.taskrc
    src: taskrc
  f_termite_config:
    dst: ~/.config/termite/config
    src: config/termite/config
  f_tmux.conf:
    dst: ~/.tmux.conf
    src: tmux.conf
  f_vimrc:
    dst: ~/.vimrc
    src: vimrc
  f_xinitrc:
    dst: ~/.xinitrc
    src: xinitrc
  f_zathurarc:
    dst: ~/.config/zathura/zathurarc
    src: config/zathura/zathurarc
  f_zprofile:
    dst: ~/.zprofile
    src: zprofile
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
  f_bspwmrc:
    src: config/bspwm/bspwmrc
    dst: ~/.config/bspwm/bspwmrc
profiles:
  general:
    variables:
      term_font_size: test
      test: 12
    dotfiles:
    - d_awesome
    - d_bin
    - d_oni2
    - d_ranger
    - d_vscode
    - f_alacritty.yml
    - f_bashrc
    - f_coc-settings.json
    - f_compton.conf
    - f_dunstrc
    - f_emoji
    - f_fa_icons
    - f_i3_config
    - f_ideavimrc
    - f_init.vim
    - f_inputrc
    - f_lfrc
    - f_linopenrc
    - f_morc_menu_v1.conf
    - f_my_neo_de.xmodmap
    - f_polybar_config
    - f_polybar_launch.sh
    - f_profile
    - f_redshift.conf
    - f_sxhkdrc
    - f_taskrc
    - f_termite_config
    - f_tmux.conf
    - f_vimrc
    - f_xinitrc
    - f_zathurarc
    - f_zprofile
    - f_zshrc
    - f_bspwmrc
  desktop:
    include:
    - general
    variables:
      wm: awesome
      term: alacritty
      term_font_size: 11
  laptop:
    include:
    - general
    variables:
      wm: bspwm
      term: alacritty
      term_font_size: 10
  jb-work:
    include:
    - general
    variables:
      wm: awesome
      term: alacritty
      term_font_size: 11
