config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_by_default: false
  longkey: false
dotfiles:
  d_fonts:
    dst: ~/.fonts
    src: fonts
  d_qpdfview:
    dst: ~/.config/qpdfview
    src: config/qpdfview
  d_ranger:
    dst: ~/.config/ranger
    src: config/ranger
  f_conkyrc:
    dst: ~/.config/conky/conkyrc
    src: config/conky/conkyrc
  f_dunstrc:
    dst: ~/.config/dunst/dunstrc
    src: config/dunst/dunstrc
  f_emoji:
    dst: ~/.emoji
    src: emoji
  f_i3_config:
    dst: ~/.i3/config
    src: i3/config
  f_jojo.zsh-theme:
    dst: ~/.oh-my-zsh/themes/jojo.zsh-theme
    src: oh-my-zsh/themes/jojo.zsh-theme
  f_morc_menu_v1.conf:
    dst: ~/.config/morc_menu/morc_menu_v1.conf
    src: config/morc_menu/morc_menu_v1.conf
  f_my_neo_de.xmodmap:
    dst: ~/my_neo_de.xmodmap
    src: my_neo_de.xmodmap
  f_polybar_config:
    dst: ~/.config/polybar/config
    src: config/polybar/config
  f_polybar_launch.sh:
    dst: ~/.config/polybar/launch.sh
    src: config/polybar/launch.sh
  f_profile:
    dst: ~/.profile
    src: profile
  f_redshift.conf:
    dst: ~/.config/redshift/redshift.conf
    src: config/redshift/redshift.conf
  f_spacemacs:
    dst: ~/.spacemacs
    src: spacemacs
  f_termite_config:
    dst: ~/.config/termite/config
    src: config/termite/config
  f_tmux.conf:
    dst: ~/.tmux.conf
    src: tmux.conf
  f_vimrc:
    dst: ~/.vimrc
    src: vimrc
  f_wallpaper.jpg:
    dst: ~/.config/wallpaper.jpg
    src: config/wallpaper.jpg
  f_xinitrc:
    dst: ~/.xinitrc
    src: xinitrc
  f_xmodmap:
    dst: ~/.Xmodmap
    src: Xmodmap
  f_xmouselessrc:
    dst: ~/.config/xmouseless/xmouselessrc
    src: config/xmouseless/xmouselessrc
  f_xresources:
    dst: ~/.Xresources
    src: Xresources
  f_zathurarc:
    dst: ~/.config/zathura/zathurarc
    src: config/zathura/zathurarc
  f_zprofile:
    dst: ~/.zprofile
    src: zprofile
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
profiles:
  desktop-i3:
    dotfiles:
    - f_xinitrc
    - f_xresources
    - f_profile
    - f_zprofile
    - f_zshrc
    - f_i3_config
    - f_spacemacs
    - f_vimrc
    - f_xmodmap
    - d_fonts
    - f_polybar_config
    - f_polybar_launch.sh
    - d_qpdfview
    - f_redshift.conf
    - f_jojo.zsh-theme
    - f_tmux.conf
    - f_termite_config
    - f_morc_menu_v1.conf
    - f_zathurarc
    - f_xmouselessrc
    - f_my_neo_de.xmodmap
    - f_dunstrc
    - f_conkyrc
    - f_emoji
    - d_ranger
  laptop-i3:
    dotfiles:
    - f_xinitrc
    - f_xresources
    - f_profile
    - f_zprofile
    - f_zshrc
    - f_i3_config
    - f_spacemacs
    - f_xmodmap
    - d_fonts
    - f_polybar_config
    - f_polybar_launch.sh
    - d_qpdfview
    - f_redshift.conf
    - f_jojo.zsh-theme
    - f_tmux.conf
    - f_termite_config
    - f_morc_menu_v1.conf
    - f_zathurarc
    - f_xmouselessrc
    - f_my_neo_de.xmodmap
    - f_dunstrc
    - f_conkyrc
    - f_emoji
    - d_ranger
  jb-work:
    dotfiles:
    - f_xinitrc
    - f_spacemacs
    - d_fonts
    - f_polybar_config
    - f_polybar_launch.sh
    - d_qpdfview
    - f_redshift.conf
    - f_tmux.conf
    - f_termite_config
    - f_morc_menu_v1.conf
    - f_zathurarc
    - f_xmouselessrc
    - f_my_neo_de.xmodmap
    - f_dunstrc
    - f_emoji
    - d_ranger
